import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "@/app/globals.css"
import Footer from "@/components/layout/Footer"
import Header from "@/components/layout/Header"
import { routing } from "@/i18n/routing"
import { notFound } from "next/navigation"
import { getMessages } from "next-intl/server"
import { NextIntlClientProvider } from "next-intl"
import ComingSoonPage from "@/components/page/ComingSoonPage"
import { DialogProvider } from "@/providers/DialogProvider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

// 오픈 날짜 설정
const OPEN_DATE = new Date("2026-02-24T00:00:00")

function isBeforeOpenDate(): boolean {
  const now = new Date()
  return now < OPEN_DATE
}

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }))
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ locale: string }>
}>) {
  const { locale } = await params

  // locale 유효성 검증
  if (!routing.locales.includes(locale as any)) {
    notFound()
  }

  // 날짜 체크: 3월 3일 전이면 ComingSoonPage만 표시
  if (isBeforeOpenDate()) {
    return (
      <html lang={locale}>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ComingSoonPage />
        </body>
      </html>
    )
  }

  // 해당 locale의 메시지 가져오기
  const messages = await getMessages()

  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextIntlClientProvider messages={messages}>
          <DialogProvider>
            <div className="w-screen h-screen overflow-y-auto thin-scrollbar">
              <Header />
              {children}
              <Footer />
            </div>
          </DialogProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
